### ISSUE TITLE
DB and cases 

### ISSUE THREAD

**Issue by MyaMorocco** [khalid-elabbadi/easyschool_dt#60]
![image](https://user-images.githubusercontent.com/42932849/52004005-65b50f00-24c6-11e9-836e-a09dac49d381.png)

![image](https://user-images.githubusercontent.com/42932849/52004050-81201a00-24c6-11e9-9978-b0bbe21dd94d.png)

![image](https://user-images.githubusercontent.com/42932849/52004216-e6740b00-24c6-11e9-879e-5d51cbdd2b6d.png)

**Comment by khalid-elabbadi** [comment]
I fixed the issue

**Comment by MyaMorocco** [comment]
Issue tested and fixed!
